server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: ENC(QUDJO3uUeeEFN3KQalY86g==)
    password: ENC(iJxDrjfB+f54C1qDCeKVXg==)

  sql:
    init:
      schema-locations: classpath:init-data/h2db/schema.sql
      data-locations: classpath:init-data/h2db/data.sql
      username: ENC(QUDJO3uUeeEFN3KQalY86g==)
      password: ENC(iJxDrjfB+f54C1qDCeKVXg==)
      mode: always
      encoding: UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console

