/** 멤버십 서비스에 필요한 기초 테이블 스크립트 **/

drop table if exists TB_ACNT;
drop table if exists TB_GRD;
drop table if exists TB_MBSP;
drop table if exists TB_MBSP_GRD;
drop table if exists TB_MBSP_FRCH;
drop table if exists TB_MY_MBSP;
drop table if exists TB_MY_MBSP_ACCUM;

/* 1. 회원 정보 (TB_ACNT) */
CREATE TABLE TB_ACNT (
    ACNT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원번호',
    ACNT_NM VARCHAR(50) NOT NULL COMMENT '회원이름',
    STATUS CHAR DEFAULT '1' COMMENT '상태 (1:사용, 9:정지, 0:탈퇴)',
    BIRTH VARCHAR(8) NOT NULL COMMENT '생년월일',
    HPHONE VARCHAR(11) NOT NULL COMMENT '휴대폰번호',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일',
    ACNT_GRD VARCHAR(10) DEFAULT 'USER' COMMENT '회원등급 (USER/SELLER/ADMIN)',
    INSERT_DATE TIMESTAMP COMMENT '등록일자',
    INSERT_USER BIGINT COMMENT '등록자ID',
    UPDATE_DATE TIMESTAMP COMMENT '수정일자',
    UPDATE_USER BIGINT COMMENT '수정자ID',
    CONSTRAINT TB_ACNT_PK PRIMARY KEY(ACNT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '회원정보';

/* 2.멤버십 정보 (TB_MBSP) */
CREATE TABLE TB_MBSP (
    MBSP_ID VARCHAR(15) NOT NULL COMMENT '멤버십ID',
    MBSP_NM VARCHAR(100) NOT NULL COMMENT '멤버십명',
    STATUS CHAR DEFAULT '1' COMMENT '상태 (1:사용, 9:정지)',
    MBSP_INFO VARCHAR(200) NOT NULL COMMENT '멤버십 안내문구',
    MBSP_IMG_URL VARCHAR(200) COMMENT '멤버십 이미지 경로',
    HOMEPAGE_URL VARCHAR(200) COMMENT '본사 홈페이지 URL',
    ACTIVE_MONTHS INT DEFAULT 3 COMMENT '적립포인트 유효개월수',
    BIGO VARCHAR(2000) COMMENT '비고',
    INSERT_DATE TIMESTAMP COMMENT '등록일자',
    INSERT_USER BIGINT COMMENT '등록자ID',
    UPDATE_DATE TIMESTAMP COMMENT '수정일자',
    UPDATE_USER BIGINT COMMENT '수정자ID',
    CONSTRAINT TB_MBSP_PK PRIMARY KEY(MBSP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '멤버십 정보';


/* 3. 멤버십 등급정보 (TB_MBSP_GRD) */
CREATE TABLE TB_MBSP_GRD (
    MBSP_ID VARCHAR(15) NOT NULL COMMENT '멤버십ID',
    MBSP_GRD_CD VARCHAR(10) NOT NULL COMMENT '멤버십 등급코드',
    GRD_UP_POINT_FR INT NOT NULL COMMENT '등업기준포인트 [FROM]',
    GRD_UP_POINT_TO INT NOT NULL COMMENT '등업기준포인트 [TO]',
    ACCUM_RAT INT NOT NULL COMMENT '적립율',
    DISC_RAT INT NOT NULL COMMENT '할인율',
    INSERT_DATE TIMESTAMP COMMENT '등록일자',
    INSERT_USER BIGINT COMMENT '등록자ID',
    UPDATE_DATE TIMESTAMP COMMENT '수정일자',
    UPDATE_USER BIGINT COMMENT '수정자ID',
    CONSTRAINT TB_MBSP_GRD_PK PRIMARY KEY(MBSP_ID, MBSP_GRD_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '멤버십 등급정보';


/* 4. 멤버십 가맹점 (TB_MBSP_FRCH) */
CREATE TABLE TB_MBSP_FRCH (
    MBSP_ID VARCHAR(15) NOT NULL COMMENT '멤버십ID',
    FRCH_ID VARCHAR(15) NOT NULL COMMENT '가맹점ID',
    FRCH_NM VARCHAR(100) NOT NULL COMMENT '가맹점명',
    STATUS CHAR DEFAULT '1' COMMENT '상태 (1:사용, 9:정지)',
    ZIP_CD VARCHAR(5) COMMENT '우편번호',
    ADDR1 VARCHAR(200) COMMENT '주소',
    ADDR2 VARCHAR(200) COMMENT '상세주소',
    TEL_NO VARCHAR(20) COMMENT '대표전화번호',
    BIGO VARCHAR(2000) COMMENT '비고',
    INSERT_DATE TIMESTAMP COMMENT '등록일자',
    INSERT_USER BIGINT COMMENT '등록자ID',
    UPDATE_DATE TIMESTAMP COMMENT '수정일자',
    UPDATE_USER BIGINT COMMENT '수정자ID',
    CONSTRAINT TB_MBSP_FRCH_PK PRIMARY KEY(MBSP_ID, FRCH_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '멤버십 가맹점정보';


/* 5. 나의 멤버십정보 (TB_MY_MBSP) */
CREATE TABLE TB_MY_MBSP (
    ACNT_ID BIGINT NOT NULL COMMENT '회원번호',
    MBSP_ID VARCHAR(15) NOT NULL COMMENT '멤버십ID',
    STATUS CHAR DEFAULT '1' COMMENT '상태 (1:사용, 0:탈퇴)',
    TOTAL_ACCUM_POINT INT Default 0 COMMENT '총 적립 포인트',
    MBSP_GRD_CD VARCHAR(10) Default 'COMMON' COMMENT '멤버십 등급코드',
    INSERT_DATE TIMESTAMP NOT NULL COMMENT '가입일자',
    WITHDRAWAL_DATE TIMESTAMP COMMENT '탈퇴일자',
    BAR_CD VARCHAR(50) NOT NULL COMMENT '멤버십 바코드번호',
    CONSTRAINT TB_MY_MBSP_PK PRIMARY KEY(ACNT_ID, MBSP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '나의 멤버십정보';



/* 6. 나의 멤버십적립내역 (TB_MY_MBSP_ACCUM) */
CREATE TABLE TB_MY_MBSP_ACCUM (
    CANCEL_BAR_CD VARCHAR(50) NOT NULL COMMENT '취소용 바코드 번호',
    STATUS CHAR DEFAULT '1' COMMENT '상태 (1:사용, 9:취소)',
    ACNT_ID BIGINT NOT NULL COMMENT '회원번호',
    MBSP_ID VARCHAR(15) NOT NULL COMMENT '멤버십ID',
    FRCH_ID VARCHAR(15) NOT NULL COMMENT '가맹점ID',
    TRADE_AMT INT NOT NULL COMMENT '거래금액',
    MBSP_GRD_CD VARCHAR(10) NOT NULL COMMENT '멤버십 등급코드',
    ACCUM_RAT INT NOT NULL COMMENT '적립율',
    ACCUM_POINT INT NOT NULL COMMENT '적립 포인트',
    EXPIRE_YMD VARCHAR(8) NOT NULL COMMENT '포인트 만료일',
    ACCUM_DATE TIMESTAMP NOT NULL COMMENT '적립일자',
    ACCUM_CANCEL_DATE TIMESTAMP COMMENT '적립취소일자',
    CONSTRAINT TB_MY_MBSP_ACCUM_PK PRIMARY KEY(CANCEL_BAR_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '나의 멤버십 적립내역';

/* 스키마 생성 */
CREATE SCHEMA MBSP;

/* seq - 바코드생성 시퀀스 */
CREATE SEQUENCE MBSP.BAR_CD_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
CYCLE;

/* MYSQL FUNCTION H2에 생성 */
DROP ALIAS IF EXISTS STR_TO_DATE;
CREATE ALIAS IF NOT EXISTS STR_TO_DATE FOR "com.franc.config.H2FunctionConfig.strToDate";
